apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  # Сгенерируйте это командой:
  # kubectl create secret docker-registry ghcr-secret \
  #   --docker-server=ghcr.io \
  #   --docker-username=o-albot \
  #   --docker-password=ваш-токен \
  #   --dry-run=client -o yaml
  .dockerconfigjson: eyJhdXRocyI6... (base64 encoded)